create table if not exists public.stock_trade_risk (
  id bigint generated by default as identity primary key,
  record_key text not null unique,
  stock_id text not null,
  market text not null check (market in ('TWSE', 'TPEx')),
  risk_type text not null check (risk_type in (
    'attention', 'disposition', 'trading_halt', 'margin_restricted',
    'short_sale_restricted', 'daytrade_restricted'
  )),
  risk_level text not null check (risk_level in ('medium', 'high', 'critical')),
  reason text not null default '',
  restrictions text not null default '',
  announced_date date,
  start_date date not null,
  end_date date,
  source text not null,
  source_url text not null,
  source_updated_at timestamptz,
  fetched_at timestamptz not null,
  is_active boolean not null default true,
  raw_data jsonb not null default '{}'::jsonb
);

create index if not exists idx_stock_trade_risk_stock
  on public.stock_trade_risk(stock_id);
create index if not exists idx_stock_trade_risk_active
  on public.stock_trade_risk(is_active);
create index if not exists idx_stock_trade_risk_type
  on public.stock_trade_risk(risk_type);
create index if not exists idx_stock_trade_risk_start
  on public.stock_trade_risk(start_date);
create index if not exists idx_stock_trade_risk_end
  on public.stock_trade_risk(end_date);
create index if not exists idx_stock_trade_risk_strategy
  on public.stock_trade_risk(is_active, risk_type, stock_id);

alter table public.stock_trade_risk enable row level security;
revoke all on table public.stock_trade_risk from anon, authenticated;
grant select on table public.stock_trade_risk to anon, authenticated;
grant all on table public.stock_trade_risk to service_role;
grant usage, select on sequence public.stock_trade_risk_id_seq to service_role;

drop policy if exists "stock_trade_risk_public_read" on public.stock_trade_risk;
create policy "stock_trade_risk_public_read"
on public.stock_trade_risk for select to anon, authenticated using (true);

comment on table public.stock_trade_risk is
'Normalized TWSE/TPEx trade-risk history. Public clients are read-only; service role performs idempotent upserts.';

create table if not exists public.trade_risk_sync_status (
  id boolean primary key default true check (id),
  status text not null check (status in ('success', 'degraded', 'failed')),
  local_total integer not null default 0,
  cloud_total integer not null default 0,
  active integer not null default 0,
  latest_source_fetched_at timestamptz,
  synced_at timestamptz,
  attempted_at timestamptz not null default now(),
  error text,
  summary jsonb not null default '{}'::jsonb
);

alter table public.trade_risk_sync_status enable row level security;
revoke all on table public.trade_risk_sync_status from anon, authenticated;
grant select on table public.trade_risk_sync_status to anon, authenticated;
grant all on table public.trade_risk_sync_status to service_role;

drop policy if exists "trade_risk_sync_status_public_read" on public.trade_risk_sync_status;
create policy "trade_risk_sync_status_public_read"
on public.trade_risk_sync_status for select to anon, authenticated using (true);

comment on table public.trade_risk_sync_status is
'Singleton audit record for the last fully verified SQLite-to-Supabase trade-risk sync.';
